name: Branch Deleted

on: delete

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
          ref: hakyll

      - name: Remove deployment for deleted branch
        run: |
          ./.github/workflows/deployment/delete.sh ${{ github.event.ref }}
