# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the hakyll branch
  push:
    # branches:
    branches-ignore:
      - gh-pages
  pull_request:
    branches-ignore:
      - gh-pages

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    strategy:
      matrix:
        stack: ["2.7.3"]
        ghc: ["8.10.7"]

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
          ref: hakyll

      - uses: haskell/actions/setup@v1
        name: Setup Haskell Stack
        with:
          ghc-version: ${{ matrix.ghc }}
          stack-version: ${{ matrix.stack }}

      - uses: actions/cache@v1
        name: Cache ~/.stack
        with:
          path: ~/.stack
          key: ${{ runner.os }}-${{ matrix.ghc }}-stack

      - name: Build dependencies
        run: stack build --system-ghc --only-dependencies

      - name: Build
        run: |
          stack build --system-ghc
          stack exec --system-ghc site build

      - name: Deploy
        run: ./.github/workflows/deploy.sh
